/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

/**
 * FileManager window:  Takes in user given values of which fields to update and
 *   how many scholars/students are in each linked excel sheet.  Input validation
 *   taken care of in DAO's and updateFile action method of STEMIDBMainWindow
 */
public class FileLoadWindow extends javax.swing.JDialog {

    private boolean updateScholars;
    private boolean updateStudents;
    
    // NOT CURRENTLY USED
    private String TotalScholars;
    private String totalStudents;
    
    /**
     * Creates new form FileManager
     */
    public FileLoadWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("File Manager");
        this.setLocationRelativeTo(null);
    }

    public boolean isUpdateScholars() 
    {
        return updateScholars;
    }
    public boolean isUpdateStudents() 
    {
        return updateStudents;
    }
    
    public String getTotalScholars()
    {
        return this.TotalScholars;
    }
    public String getTotalStudents()
    {
        return this.totalStudents;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainPanel = new javax.swing.JPanel();
        jScholarCheckBox = new javax.swing.JCheckBox();
        jStudentCheckBox = new javax.swing.JCheckBox();
        jInstructionsLabel1 = new javax.swing.JLabel();
        jUpdateFilesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScholarCheckBox.setText("Scholars");
        jScholarCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScholarCheckBoxActionPerformed(evt);
            }
        });

        jStudentCheckBox.setText("Students");

        jInstructionsLabel1.setText(" Select Fields to Update from Excel Spreadsheet ");
        jInstructionsLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jUpdateFilesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jUpdateFilesButton.setText("Update Files");
        jUpdateFilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateFilesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScholarCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jStudentCheckBox)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainPanelLayout.createSequentialGroup()
                        .addComponent(jInstructionsLabel1)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainPanelLayout.createSequentialGroup()
                        .addComponent(jUpdateFilesButton)
                        .addGap(102, 102, 102))))
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jInstructionsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jScholarCheckBox)
                    .addComponent(jStudentCheckBox))
                .addGap(18, 18, 18)
                .addComponent(jUpdateFilesButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUpdateFilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateFilesButtonActionPerformed
        this.updateScholars = this.jScholarCheckBox.isSelected();
        this.updateStudents = this.jStudentCheckBox.isSelected();
        this.dispose();
    }//GEN-LAST:event_jUpdateFilesButtonActionPerformed

    private void jScholarCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScholarCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScholarCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileLoadWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileLoadWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileLoadWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileLoadWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FileLoadWindow dialog = new FileLoadWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jInstructionsLabel1;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JCheckBox jScholarCheckBox;
    private javax.swing.JCheckBox jStudentCheckBox;
    private javax.swing.JButton jUpdateFilesButton;
    // End of variables declaration//GEN-END:variables
}
